Repository fcpkata/user, pull requests merged in 2020-07, with the labels that each got.

#1 Updated java version in Dockerfile
  Dockerfile
  charts/user/values.yaml
Labels: approved, lgtm, size/XS

#2 Updated README
  README.md
Labels: approved

#3 CI/CD config
  OWNERS
  OWNERS_ALIASES
  charts/user/values.yaml
Labels: approved, lgtm, size/S

#4 Updated CI/CD config
  OWNERS
  charts/user/values.yaml
Labels: approved, size/XS

#5 Deleted old deployment files
  deploy/Dockerfile
  deploy/user-deployment.yaml
Labels: approved, size/S

#6 added actuator depdendencies and updated actuator path in probe path
  build.gradle
  charts/user/values.yaml
  src/main/java/com/shoppingcart/user/controller/UserController.java
  src/main/resources/application.properties
  src/test/java/com/shoppingcart/user/controller/UserControllerAcceptanceTest.java
Labels: approved, lgtm, size/S
